name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Or your project's main branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/website/package-lock.json # Assuming package-lock.json exists or will exist

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Docusaurus dependencies
        working-directory: ./docs/website
        run: npm ci # Use clean install for CI

      - name: Build Docusaurus site
        working-directory: ./docs/website
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/website/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
