name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and test the application
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run tests
      run: bun test
      
    - name: Build application
      run: bun run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: .next/
        retention-days: 1

  # Build documentation
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build documentation
      run: bun run docs:build
      
    - name: Upload docs artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs-build
        path: docs/
        retention-days: 1

  # Deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build, build-docs]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download app artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-build
        path: .next/
        
    - name: Download docs artifacts
      uses: actions/download-artifact@v4
      with:
        name: docs-build
        path: docs/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Create static site
      run: |
        mkdir -p public
        cp -r docs/* public/
        echo "<!DOCTYPE html><html><head><title>Aran API Sentinel</title><meta http-equiv='refresh' content='0;url=/docs/'></head><body>Redirecting to documentation...</body></html>" > public/index.html
        
    - name: Upload site
      uses: actions/upload-pages-artifact@v3
      with:
        path: public
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 