# GitHub Pages configuration
# This file configures the static site generation for GitHub Pages

# Build configuration
build:
  output: .fumadocs
  base: /
  clean: true

# Site configuration
site:
  title: Aran API Sentinel Documentation
  description: Complete documentation for Aran API Sentinel - Multi-tenant API security and governance platform
  url: https://radhi1991.github.io/aran
  basePath: /aran

# Navigation
navigation:
  - title: Getting Started
    items:
      - title: Installation
        path: /getting-started/installation
      - title: Multi-Tenant Setup
        path: /multi-tenant/setup
  - title: Features
    items:
      - title: Overview
        path: /features/overview
      - title: API Discovery
        path: /features/api-discovery
      - title: Threat Detection
        path: /features/threat-detection
      - title: API Catalog
        path: /features/api-catalog
      - title: MCP Security
        path: /features/mcp-security
  - title: Development
    items:
      - title: Roadmap
        path: /roadmap
      - title: API Reference
        path: /api-reference
      - title: Security Guide
        path: /security-guide

# Theme configuration
theme:
  primary: "#2563eb"
  secondary: "#64748b"
  accent: "#f59e0b"
  background: "#ffffff"
  text: "#1f2937"

# SEO
seo:
  title: Aran API Sentinel Documentation
  description: Complete documentation for Aran API Sentinel - Multi-tenant API security and governance platform
  keywords:
    - API Security
    - API Governance
    - Multi-Tenant
    - MCP Security
    - Model Context Protocol
    - API Discovery
    - Threat Detection
  og:
    type: website
    image: /screenshots/dashboard.png
  twitter:
    card: summary_large_image
    image: /screenshots/dashboard.png 